/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IMirrorENSRegistrarInterface extends ethers.utils.Interface {
  functions: {
    "changeLabelOwner(string,address)": FunctionFragment;
    "changeRootNodeOwner(address)": FunctionFragment;
    "labelOwner(string)": FunctionFragment;
    "register(string,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "changeLabelOwner",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "changeRootNodeOwner",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "labelOwner", values: [string]): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "changeLabelOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeRootNodeOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "labelOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;

  events: {};
}

export class IMirrorENSRegistrar extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IMirrorENSRegistrarInterface;

  functions: {
    changeLabelOwner(
      label_: string,
      newOwner_: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "changeLabelOwner(string,address)"(
      label_: string,
      newOwner_: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    changeRootNodeOwner(
      newOwner_: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "changeRootNodeOwner(address)"(
      newOwner_: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    labelOwner(label: string, overrides?: CallOverrides): Promise<[string]>;

    "labelOwner(string)"(
      label: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    register(
      label_: string,
      owner_: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "register(string,address)"(
      label_: string,
      owner_: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  changeLabelOwner(
    label_: string,
    newOwner_: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "changeLabelOwner(string,address)"(
    label_: string,
    newOwner_: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  changeRootNodeOwner(
    newOwner_: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "changeRootNodeOwner(address)"(
    newOwner_: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  labelOwner(label: string, overrides?: CallOverrides): Promise<string>;

  "labelOwner(string)"(
    label: string,
    overrides?: CallOverrides
  ): Promise<string>;

  register(
    label_: string,
    owner_: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "register(string,address)"(
    label_: string,
    owner_: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    changeLabelOwner(
      label_: string,
      newOwner_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "changeLabelOwner(string,address)"(
      label_: string,
      newOwner_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    changeRootNodeOwner(
      newOwner_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "changeRootNodeOwner(address)"(
      newOwner_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    labelOwner(label: string, overrides?: CallOverrides): Promise<string>;

    "labelOwner(string)"(
      label: string,
      overrides?: CallOverrides
    ): Promise<string>;

    register(
      label_: string,
      owner_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "register(string,address)"(
      label_: string,
      owner_: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    changeLabelOwner(
      label_: string,
      newOwner_: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "changeLabelOwner(string,address)"(
      label_: string,
      newOwner_: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    changeRootNodeOwner(
      newOwner_: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "changeRootNodeOwner(address)"(
      newOwner_: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    labelOwner(label: string, overrides?: CallOverrides): Promise<BigNumber>;

    "labelOwner(string)"(
      label: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    register(
      label_: string,
      owner_: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "register(string,address)"(
      label_: string,
      owner_: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    changeLabelOwner(
      label_: string,
      newOwner_: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "changeLabelOwner(string,address)"(
      label_: string,
      newOwner_: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    changeRootNodeOwner(
      newOwner_: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "changeRootNodeOwner(address)"(
      newOwner_: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    labelOwner(
      label: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "labelOwner(string)"(
      label: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    register(
      label_: string,
      owner_: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "register(string,address)"(
      label_: string,
      owner_: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
