/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IENS } from "../IENS";

export class IENS__factory {
  static connect(address: string, signerOrProvider: Signer | Provider): IENS {
    return new Contract(address, _abi, signerOrProvider) as IENS;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_node",
        type: "bytes32",
      },
    ],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
